// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HandlerInterface is an autogenerated mock type for the HandlerInterface type
type HandlerInterface struct {
	mock.Mock
}

// ICMP provides a mock function with given fields: ip, count, timeout, privileged
func (_m *HandlerInterface) ICMP(ip string, count int, timeout time.Duration, privileged bool) error {
	ret := _m.Called(ip, count, timeout, privileged)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, time.Duration, bool) error); ok {
		r0 = rf(ip, count, timeout, privileged)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Telnet provides a mock function with given fields: protocol, address, timeout
func (_m *HandlerInterface) Telnet(protocol string, address string, timeout time.Duration) error {
	ret := _m.Called(protocol, address, timeout)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) error); ok {
		r0 = rf(protocol, address, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
