package constant

const (
	Check           = "check"
	Shell           = "shell"
	Initialize      = "initialize"
	Compile         = "compile"
	Start           = "start"
	Stop            = "stop"
	Enable          = "enable"
	Enabled         = "enabled"
	Parses          = "parses"
	Config          = "config"
	Optimize        = "optimize"
	Gcc             = "^gcc-[0-9]"
	RpmSearch       = "rpm -qa|grep"
	YumInstall      = "yum install -y"
	Pass            = "pass"
	Install         = "install"
	Error           = "error"
	Redis           = "redis"
	Remote          = "remote"
	Local           = "local"
	LoopbackAddress = "127.0.0.1"
	Docker          = "docker"
	Parallel        = "Parallel"
	Scp             = "scp"
	Service         = "service"
	Parse           = "parse"
	Reload          = "reload"
	Write           = "write"
	File            = "file"
	Decompress      = "decompress"
	systemctl       = "systemctl"
	start           = "start"
	status          = "status"
	enable          = "enable"
	Kernel          = "kernel"
	Localhost       = "localhost"
)
